package ca.shadowfoxtv.taskkiller;

import android.app.Activity; import android.app.ActivityManager; import android.content.Context; import android.content.Intent; import android.content.pm.PackageManager; import android.net.ConnectivityManager; import android.net.Network; import android.net.NetworkCapabilities; import android.os.Build; import android.os.Bundle; import android.provider.Settings; import android.view.View; import android.widget.Button; import android.widget.ProgressBar; import android.widget.Switch; import android.widget.TextView;
import java.net.InetSocketAddress; import java.net.Socket; import java.util.Arrays; import java.util.HashSet; import java.util.List; import java.util.Set; import java.util.concurrent.ExecutorService; import java.util.concurrent.Executors;

public class V4DashboardActivity extends Activity {
 private final ExecutorService worker=Executors.newSingleThreadExecutor(); private final Set<String> whitelist=new HashSet<>(); private TextView networkText,speedText,bufferText,resultTitle,resultDetail,versionText; private ProgressBar bufferProgress; private SpeedGaugeView gauge; private LatencyGraphView graph; private Button optimizeButton,bufferButton; private Switch fixPing; private volatile boolean busy;
 @Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_v4_dashboard);networkText=findViewById(R.id.networkTextV4);speedText=findViewById(R.id.speedText);bufferText=findViewById(R.id.bufferText);bufferProgress=findViewById(R.id.bufferProgress);gauge=findViewById(R.id.speedGauge);graph=findViewById(R.id.latencyGraph);resultTitle=findViewById(R.id.resultTitleV4);resultDetail=findViewById(R.id.resultDetailV4);versionText=findViewById(R.id.versionTextV4);optimizeButton=findViewById(R.id.optimizeButtonV4);bufferButton=findViewById(R.id.bufferButtonV4);fixPing=findViewById(R.id.fixPingSwitch);buildWhitelist();versionText.setText("v"+BuildConfig.VERSION_NAME+" • NETWORK OPTIMIZER");optimizeButton.setOnClickListener(v->runFullOptimization());bufferButton.setOnClickListener(v->runBufferOptimization());fixPing.setOnCheckedChangeListener((v,on)->{if(on)runPingTest();});addFocus(optimizeButton);addFocus(bufferButton);addFocus(fixPing);addFocus(findViewById(R.id.bufferCard));addFocus(findViewById(R.id.latencyCard));optimizeButton.requestFocus();refreshNetwork();runPingTest();}
 private void buildWhitelist(){whitelist.addAll(Arrays.asList(getPackageName(),"com.android.systemui","com.android.settings","com.google.android.tvlauncher","com.google.android.apps.tv.launcherx","com.amazon.tv.launcher","com.google.android.tv.remote.service"));String ime=Settings.Secure.getString(getContentResolver(),Settings.Secure.DEFAULT_INPUT_METHOD);if(ime!=null&&ime.contains("/"))whitelist.add(ime.substring(0,ime.indexOf('/')));try{Intent home=new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_HOME);if(getPackageManager().resolveActivity(home,PackageManager.MATCH_DEFAULT_ONLY)!=null)whitelist.add(getPackageManager().resolveActivity(home,PackageManager.MATCH_DEFAULT_ONLY).activityInfo.packageName);}catch(Exception ignored){}try{ConnectivityManager cm=(ConnectivityManager)getSystemService(CONNECTIVITY_SERVICE);Network n=cm.getActiveNetwork();NetworkCapabilities nc=n==null?null:cm.getNetworkCapabilities(n);if(nc!=null&&nc.hasTransport(NetworkCapabilities.TRANSPORT_VPN)&&Build.VERSION.SDK_INT>=29){String[] pkgs=getPackageManager().getPackagesForUid(nc.getOwnerUid());if(pkgs!=null)whitelist.addAll(Arrays.asList(pkgs));}}catch(Exception ignored){}}
 public void runFullOptimization(){if(busy)return;busy=true;optimizeButton.setEnabled(false);optimizeButton.setText("OPTIMIZING…");resultTitle.setText("OPTIMIZATION RUNNING");worker.execute(()->{ActivityManager am=(ActivityManager)getSystemService(Context.ACTIVITY_SERVICE);int attempted=0;long before=availableRam();if(am!=null){List<ActivityManager.RunningAppProcessInfo> running=am.getRunningAppProcesses();if(running!=null)for(ActivityManager.RunningAppProcessInfo proc:running){if(proc.pkgList==null)continue;for(String pkg:proc.pkgList){if(isWhitelisted(pkg))continue;try{am.killBackgroundProcesses(pkg);attempted++;}catch(Exception ignored){}}}}long ping=measurePing();try{Thread.sleep(500);}catch(InterruptedException e){Thread.currentThread().interrupt();}long recovered=Math.max(0,availableRam()-before);int count=attempted;runOnUiThread(()->{busy=false;optimizeButton.setEnabled(true);optimizeButton.setText("RUN FULL OPTIMIZATION");graph.addSample(ping);refreshNetworkWithPing(ping);resultTitle.setText("OPTIMIZATION COMPLETE");if(Build.VERSION.SDK_INT>=34)resultDetail.setText("Scan complete • Android 14+ restricts third-party process termination • Ping "+fmtPing(ping));else resultDetail.setText(count+" background packages requested • "+formatMb(recovered)+" RAM recovered • Ping "+fmtPing(ping));});});}
 private boolean isWhitelisted(String pkg){return pkg==null||whitelist.contains(pkg)||pkg.startsWith("android")||pkg.startsWith("com.android.");}
 private void runBufferOptimization(){bufferProgress.setProgress(0);bufferText.setText("REFRESHING NETWORK");runPingTest();worker.execute(()->{try{Thread.sleep(350);}catch(Exception ignored){}runOnUiThread(()->{bufferProgress.setProgress(100);bufferText.setText("NETWORK REFRESHED");});});}
 private void runPingTest(){worker.execute(()->{long p=measurePing();runOnUiThread(()->{graph.addSample(p);refreshNetworkWithPing(p);});});}
 private long measurePing(){long start=System.nanoTime();try(Socket s=new Socket()){s.connect(new InetSocketAddress("1.1.1.1",443),1800);return(System.nanoTime()-start)/1_000_000L;}catch(Exception e){return-1;}}
 private void refreshNetwork(){refreshNetworkWithPing(-1);} private void refreshNetworkWithPing(long ping){ConnectivityManager cm=(ConnectivityManager)getSystemService(CONNECTIVITY_SERVICE);Network n=cm.getActiveNetwork();NetworkCapabilities nc=n==null?null:cm.getNetworkCapabilities(n);boolean online=nc!=null&&nc.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET);networkText.setText(online?"NETWORK ONLINE":"NETWORK OFFLINE");int mbps=nc==null?0:Math.max(0,nc.getLinkDownstreamBandwidthKbps()/1000);gauge.setMbps(mbps);speedText.setText("NETWORK LINK ESTIMATE\n"+(mbps>0?mbps+" Mbps":"— Mbps")+"\nDOWNLOAD CAPACITY\nPING: "+fmtPing(ping));int pressure=memoryPressure();bufferProgress.setProgress(pressure);bufferText.setText(pressure+"% MEMORY LOAD");}
 private int memoryPressure(){ActivityManager am=(ActivityManager)getSystemService(ACTIVITY_SERVICE);ActivityManager.MemoryInfo mi=new ActivityManager.MemoryInfo();if(am==null)return 0;am.getMemoryInfo(mi);return mi.totalMem==0?0:(int)(((mi.totalMem-mi.availMem)*100L)/mi.totalMem);} private long availableRam(){ActivityManager am=(ActivityManager)getSystemService(ACTIVITY_SERVICE);ActivityManager.MemoryInfo mi=new ActivityManager.MemoryInfo();if(am==null)return 0;am.getMemoryInfo(mi);return mi.availMem;} private String formatMb(long b){return String.format(java.util.Locale.US,"%.0f MB",b/(1024.0*1024.0));}private String fmtPing(long p){return p>=0?p+" ms":"— ms";}
 private void addFocus(View v){if(v==null)return;v.setOnFocusChangeListener((x,f)->{x.animate().scaleX(f?1.04f:1f).scaleY(f?1.04f:1f).setDuration(100).start();x.setElevation(f?18f:2f);});}
 @Override protected void onDestroy(){worker.shutdownNow();super.onDestroy();}
}